// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
var __defProp = Object.defineProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// <define:import.meta.env>
var init_define_import_meta_env = __esm({
  "<define:import.meta.env>"() {
  }
});

// src/contracts/BloomBetting.ts
var BloomBetting_exports = {};
__export(BloomBetting_exports, {
  BLOOM_BETTING_ABI: () => BLOOM_BETTING_ABI,
  BLOOM_BETTING_ADDRESS: () => BLOOM_BETTING_ADDRESS,
  BLOOM_TOKEN_ADDRESS: () => BLOOM_TOKEN_ADDRESS,
  BetResult: () => BetResult,
  Direction: () => Direction,
  ERC20_ABI: () => ERC20_ABI,
  ORACLE_ADDRESS: () => ORACLE_ADDRESS
});
var BLOOM_BETTING_ADDRESS, BLOOM_TOKEN_ADDRESS, ORACLE_ADDRESS, BLOOM_BETTING_ABI, ERC20_ABI, Direction, BetResult;
var init_BloomBetting = __esm({
  "src/contracts/BloomBetting.ts"() {
    init_define_import_meta_env();
    BLOOM_BETTING_ADDRESS = "0x9cE39DDf290094e9915E2D908b6D99e33167c977";
    BLOOM_TOKEN_ADDRESS = "0xa07e759da6b3d4d75ed76f92fbcb867b9c145b07";
    ORACLE_ADDRESS = "0xc6340F29b11F450877741a2f61A04D31Cb44d9B1";
    BLOOM_BETTING_ABI = [
      { inputs: [{ internalType: "address", name: "_bloomToken", type: "address" }, { internalType: "address", name: "_priceOracle", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
      { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
      { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
      { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
      { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "SafeERC20FailedOperation", type: "error" },
      { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "roundId", type: "uint256" }, { indexed: true, internalType: "uint256", name: "betId", type: "uint256" }, { indexed: true, internalType: "address", name: "user", type: "address" }, { indexed: false, internalType: "enum BloomBetting.Direction", name: "direction", type: "uint8" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "BetPlaced", type: "event" },
      { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "to", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "HouseProfitsWithdrawn", type: "event" },
      { anonymous: false, inputs: [{ indexed: false, internalType: "uint256", name: "oldMinimum", type: "uint256" }, { indexed: false, internalType: "uint256", name: "newMinimum", type: "uint256" }], name: "MinimumStakeUpdated", type: "event" },
      { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "oldOracle", type: "address" }, { indexed: false, internalType: "address", name: "newOracle", type: "address" }], name: "OracleUpdated", type: "event" },
      { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "previousOwner", type: "address" }, { indexed: true, internalType: "address", name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
      { anonymous: false, inputs: [{ indexed: false, internalType: "bool", name: "isPaused", type: "bool" }], name: "Paused", type: "event" },
      { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "roundId", type: "uint256" }, { indexed: false, internalType: "uint256", name: "totalRefunded", type: "uint256" }], name: "RoundCancelled", type: "event" },
      { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "roundId", type: "uint256" }, { indexed: false, internalType: "enum BloomBetting.Direction", name: "result", type: "uint8" }, { indexed: false, internalType: "uint256", name: "endPrice", type: "uint256" }, { indexed: false, internalType: "uint256", name: "totalPayouts", type: "uint256" }], name: "RoundSettled", type: "event" },
      { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "roundId", type: "uint256" }, { indexed: false, internalType: "uint256", name: "startTime", type: "uint256" }, { indexed: false, internalType: "uint256", name: "startPrice", type: "uint256" }], name: "RoundStarted", type: "event" },
      { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "user", type: "address" }, { indexed: false, internalType: "uint256", name: "streak", type: "uint256" }], name: "StreakUpdated", type: "event" },
      { inputs: [], name: "BETTING_CUTOFF", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "HOUSE_EDGE_BP", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "PAYOUT_MULTIPLIER", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "ROUND_DURATION", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "", type: "uint256" }], name: "betsById", outputs: [{ internalType: "uint256", name: "betId", type: "uint256" }, { internalType: "uint256", name: "roundId", type: "uint256" }, { internalType: "address", name: "user", type: "address" }, { internalType: "enum BloomBetting.Direction", name: "direction", type: "uint8" }, { internalType: "uint256", name: "amount", type: "uint256" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "enum BloomBetting.BetResult", name: "result", type: "uint8" }, { internalType: "uint256", name: "payout", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "bloomToken", outputs: [{ internalType: "contract IERC20", name: "", type: "address" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "currentRoundId", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_roundId", type: "uint256" }], name: "emergencyCancelRound", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_betId", type: "uint256" }], name: "getBet", outputs: [{ components: [{ internalType: "uint256", name: "betId", type: "uint256" }, { internalType: "uint256", name: "roundId", type: "uint256" }, { internalType: "address", name: "user", type: "address" }, { internalType: "enum BloomBetting.Direction", name: "direction", type: "uint8" }, { internalType: "uint256", name: "amount", type: "uint256" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "enum BloomBetting.BetResult", name: "result", type: "uint8" }, { internalType: "uint256", name: "payout", type: "uint256" }], internalType: "struct BloomBetting.Bet", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "getCurrentPools", outputs: [{ internalType: "uint256", name: "upPool", type: "uint256" }, { internalType: "uint256", name: "downPool", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "getCurrentRound", outputs: [{ components: [{ internalType: "uint256", name: "roundId", type: "uint256" }, { internalType: "uint256", name: "startTime", type: "uint256" }, { internalType: "uint256", name: "endTime", type: "uint256" }, { internalType: "uint256", name: "startPrice", type: "uint256" }, { internalType: "uint256", name: "endPrice", type: "uint256" }, { internalType: "uint256", name: "totalUpPool", type: "uint256" }, { internalType: "uint256", name: "totalDownPool", type: "uint256" }, { internalType: "enum BloomBetting.Direction", name: "result", type: "uint8" }, { internalType: "bool", name: "resolved", type: "bool" }], internalType: "struct BloomBetting.Round", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "getCurrentRoundBetCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "getHouseBalance", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_roundId", type: "uint256" }], name: "getRound", outputs: [{ components: [{ internalType: "uint256", name: "roundId", type: "uint256" }, { internalType: "uint256", name: "startTime", type: "uint256" }, { internalType: "uint256", name: "endTime", type: "uint256" }, { internalType: "uint256", name: "startPrice", type: "uint256" }, { internalType: "uint256", name: "endPrice", type: "uint256" }, { internalType: "uint256", name: "totalUpPool", type: "uint256" }, { internalType: "uint256", name: "totalDownPool", type: "uint256" }, { internalType: "enum BloomBetting.Direction", name: "result", type: "uint8" }, { internalType: "bool", name: "resolved", type: "bool" }], internalType: "struct BloomBetting.Round", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_roundId", type: "uint256" }], name: "getRoundBetIds", outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_roundId", type: "uint256" }], name: "getRoundBets", outputs: [{ components: [{ internalType: "uint256", name: "betId", type: "uint256" }, { internalType: "uint256", name: "roundId", type: "uint256" }, { internalType: "address", name: "user", type: "address" }, { internalType: "enum BloomBetting.Direction", name: "direction", type: "uint8" }, { internalType: "uint256", name: "amount", type: "uint256" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "enum BloomBetting.BetResult", name: "result", type: "uint8" }, { internalType: "uint256", name: "payout", type: "uint256" }], internalType: "struct BloomBetting.Bet[]", name: "", type: "tuple[]" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "getTimeRemaining", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "address", name: "_user", type: "address" }], name: "getUserBetIds", outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "address", name: "_user", type: "address" }], name: "getUserStats", outputs: [{ components: [{ internalType: "uint256", name: "totalBets", type: "uint256" }, { internalType: "uint256", name: "totalWins", type: "uint256" }, { internalType: "uint256", name: "totalLosses", type: "uint256" }, { internalType: "uint256", name: "totalStaked", type: "uint256" }, { internalType: "uint256", name: "totalProfits", type: "uint256" }, { internalType: "uint256", name: "currentStreak", type: "uint256" }, { internalType: "uint256", name: "lastPlayedDay", type: "uint256" }], internalType: "struct BloomBetting.UserStats", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "", type: "uint256" }, { internalType: "address", name: "", type: "address" }], name: "hasUserBetInRound", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "address", name: "_user", type: "address" }], name: "hasUserBetThisRound", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "isBettingOpen", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "minimumStake", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "nextBetId", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "paused", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "enum BloomBetting.Direction", name: "_direction", type: "uint8" }, { internalType: "uint256", name: "_amount", type: "uint256" }], name: "placeBet", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [], name: "priceOracle", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "uint256", name: "", type: "uint256" }, { internalType: "uint256", name: "", type: "uint256" }], name: "roundBetIds", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "", type: "uint256" }], name: "rounds", outputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }, { internalType: "uint256", name: "startTime", type: "uint256" }, { internalType: "uint256", name: "endTime", type: "uint256" }, { internalType: "uint256", name: "startPrice", type: "uint256" }, { internalType: "uint256", name: "endPrice", type: "uint256" }, { internalType: "uint256", name: "totalUpPool", type: "uint256" }, { internalType: "uint256", name: "totalDownPool", type: "uint256" }, { internalType: "enum BloomBetting.Direction", name: "result", type: "uint8" }, { internalType: "bool", name: "resolved", type: "bool" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_newMinimum", type: "uint256" }], name: "setMinimumStake", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "bool", name: "_paused", type: "bool" }], name: "setPaused", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "address", name: "_newOracle", type: "address" }], name: "setPriceOracle", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_roundId", type: "uint256" }, { internalType: "uint256", name: "_endPrice", type: "uint256" }], name: "settleRound", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_startPrice", type: "uint256" }], name: "startRound", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "address", name: "", type: "address" }, { internalType: "uint256", name: "", type: "uint256" }], name: "userBetIds", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "address", name: "", type: "address" }], name: "userStats", outputs: [{ internalType: "uint256", name: "totalBets", type: "uint256" }, { internalType: "uint256", name: "totalWins", type: "uint256" }, { internalType: "uint256", name: "totalLosses", type: "uint256" }, { internalType: "uint256", name: "totalStaked", type: "uint256" }, { internalType: "uint256", name: "totalProfits", type: "uint256" }, { internalType: "uint256", name: "currentStreak", type: "uint256" }, { internalType: "uint256", name: "lastPlayedDay", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "address", name: "_to", type: "address" }, { internalType: "uint256", name: "_amount", type: "uint256" }], name: "withdrawHouseProfits", outputs: [], stateMutability: "nonpayable", type: "function" }
    ];
    ERC20_ABI = [
      { inputs: [{ internalType: "address", name: "spender", type: "address" }, { internalType: "uint256", name: "amount", type: "uint256" }], name: "approve", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "balanceOf", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "address", name: "owner", type: "address" }, { internalType: "address", name: "spender", type: "address" }], name: "allowance", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "decimals", outputs: [{ internalType: "uint8", name: "", type: "uint8" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "symbol", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" }
    ];
    Direction = /* @__PURE__ */ ((Direction2) => {
      Direction2[Direction2["None"] = 0] = "None";
      Direction2[Direction2["Up"] = 1] = "Up";
      Direction2[Direction2["Down"] = 2] = "Down";
      return Direction2;
    })(Direction || {});
    BetResult = /* @__PURE__ */ ((BetResult2) => {
      BetResult2[BetResult2["Pending"] = 0] = "Pending";
      BetResult2[BetResult2["Win"] = 1] = "Win";
      BetResult2[BetResult2["Lose"] = 2] = "Lose";
      return BetResult2;
    })(BetResult || {});
  }
});

// lovable-mcp-supabase-entry.ts
init_define_import_meta_env();

// src/lib/mcp/index.ts
init_define_import_meta_env();
import { defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/get-current-round.ts
init_define_import_meta_env();
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/chain.ts
init_define_import_meta_env();
init_BloomBetting();
import { createPublicClient, http } from "npm:viem@^2.43.3";
import { base } from "npm:viem@^2.43.3/chains";
function publicClient() {
  return createPublicClient({ chain: base, transport: http("https://mainnet.base.org") });
}
async function readBetting(functionName, args = []) {
  const client = publicClient();
  const { BLOOM_BETTING_ABI: BLOOM_BETTING_ABI2, BLOOM_BETTING_ADDRESS: BLOOM_BETTING_ADDRESS2 } = await Promise.resolve().then(() => (init_BloomBetting(), BloomBetting_exports));
  return client.readContract({
    address: BLOOM_BETTING_ADDRESS2,
    abi: BLOOM_BETTING_ABI2,
    functionName,
    args
  });
}
async function readToken(functionName, args = []) {
  const client = publicClient();
  const { BLOOM_TOKEN_ADDRESS: BLOOM_TOKEN_ADDRESS2, ERC20_ABI: ERC20_ABI2 } = await Promise.resolve().then(() => (init_BloomBetting(), BloomBetting_exports));
  return client.readContract({
    address: BLOOM_TOKEN_ADDRESS2,
    abi: ERC20_ABI2,
    functionName,
    args
  });
}
function formatPrice8(value) {
  return Number(value) / 1e8;
}
function formatBloom(value) {
  return Number(value) / 1e18;
}
function directionLabel(value) {
  return value === 1 ? "up" : value === 2 ? "down" : "none";
}

// src/lib/mcp/tools/get-current-round.ts
var get_current_round_default = defineTool({
  name: "get_current_round",
  title: "Get current round",
  description: "Read the live ETH prediction round on Base: round id, start price, seconds remaining, whether betting is still open, the UP/DOWN $BLOOM pools and the number of bets placed.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const [round, timeRemaining, bettingOpen, betCount, minimumStake] = await Promise.all([
      readBetting("getCurrentRound"),
      readBetting("getTimeRemaining"),
      readBetting("isBettingOpen"),
      readBetting("getCurrentRoundBetCount"),
      readBetting("minimumStake")
    ]);
    const upPool = formatBloom(round.totalUpPool);
    const downPool = formatBloom(round.totalDownPool);
    const total = upPool + downPool;
    const data = {
      roundId: Number(round.roundId),
      market: "ETH",
      stakeToken: "BLOOM",
      startPriceUsd: formatPrice8(round.startPrice),
      startTime: Number(round.startTime),
      endTime: Number(round.endTime),
      secondsRemaining: Number(timeRemaining),
      bettingOpen: Boolean(bettingOpen),
      resolved: Boolean(round.resolved),
      result: directionLabel(Number(round.result)),
      upPoolBloom: upPool,
      downPoolBloom: downPool,
      upSharePercent: total > 0 ? Math.round(upPool / total * 100) : 50,
      downSharePercent: total > 0 ? Math.round(downPool / total * 100) : 50,
      betCount: Number(betCount),
      minimumStakeBloom: formatBloom(minimumStake),
      payoutMultiplier: 2
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-round.ts
init_define_import_meta_env();
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";
var get_round_default = defineTool2({
  name: "get_round",
  title: "Get a settled round",
  description: "Read any past or present round by id, including start price, end price, the settled result (up/down/none) and the final $BLOOM pools.",
  inputSchema: {
    roundId: z.number().int().positive().describe("The round id to read.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ roundId }) => {
    const round = await readBetting("getRound", [BigInt(roundId)]);
    const data = {
      roundId: Number(round.roundId),
      market: "ETH",
      startTime: Number(round.startTime),
      endTime: Number(round.endTime),
      startPriceUsd: formatPrice8(round.startPrice),
      endPriceUsd: formatPrice8(round.endPrice),
      resolved: Boolean(round.resolved),
      result: directionLabel(Number(round.result)),
      upPoolBloom: formatBloom(round.totalUpPool),
      downPoolBloom: formatBloom(round.totalDownPool)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-player-stats.ts
init_define_import_meta_env();
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var ADDRESS = z2.string().describe("Base wallet address of the player, e.g. 0x1234...abcd.");
var get_player_stats_default = defineTool3({
  name: "get_player_stats",
  title: "Get player stats",
  description: "Read on-chain prediction stats for a wallet: total bets, wins, losses, current streak, best streak, amount staked and total won in $BLOOM. Also reports whether that wallet already bet in the current round.",
  inputSchema: { address: ADDRESS },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ address }) => {
    if (!/^0x[a-fA-F0-9]{40}$/.test(address)) {
      return { content: [{ type: "text", text: "Invalid Base wallet address." }], isError: true };
    }
    const [stats, round] = await Promise.all([
      readBetting("getUserStats", [address]),
      readBetting("getCurrentRound")
    ]);
    const hasBetThisRound = await readBetting("hasUserBetInRound", [round.roundId, address]);
    const totalBets = Number(stats.totalBets ?? 0);
    const totalWins = Number(stats.totalWins ?? 0);
    const data = {
      address,
      totalBets,
      totalWins,
      totalLosses: Number(stats.totalLosses ?? 0),
      winRatePercent: totalBets > 0 ? Math.round(totalWins / totalBets * 1e3) / 10 : 0,
      currentStreak: Number(stats.currentStreak ?? 0),
      bestStreak: Number(stats.bestStreak ?? 0),
      totalStakedBloom: stats.totalStaked !== void 0 ? formatBloom(stats.totalStaked) : 0,
      totalWonBloom: stats.totalWon !== void 0 ? formatBloom(stats.totalWon) : 0,
      currentRoundId: Number(round.roundId),
      hasBetThisRound: Boolean(hasBetThisRound)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
init_define_import_meta_env();
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
init_define_import_meta_env();
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-leaderboard.ts
var get_leaderboard_default = defineTool4({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Read the public prediction leaderboard for a period (24h, 7d, 30d or all): wallet, bets, wins, losses, win rate, staked, payout and profit in $BLOOM.",
  inputSchema: {
    period: z3.enum(["24h", "7d", "30d", "all"]).describe("Time window for the ranking."),
    limit: z3.number().int().min(1).max(50).optional().describe("How many rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ period, limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.rpc("get_leaderboard", { period });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).slice(0, limit ?? 10).map((row, i) => ({
      rank: i + 1,
      wallet: row.wallet_address,
      totalBets: row.total_bets,
      totalWins: row.total_wins,
      totalLosses: row.total_losses,
      winRatePercent: Number(row.win_rate ?? 0),
      stakedBloom: Number(row.staked ?? 0),
      payoutBloom: Number(row.payout ?? 0),
      profitBloom: Number(row.profit ?? 0)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ period, rows }, null, 2) }],
      structuredContent: { period, rows }
    };
  }
});

// src/lib/mcp/tools/get-bloom-market.ts
init_define_import_meta_env();
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.4";
var get_bloom_market_default = defineTool5({
  name: "get_bloom_market",
  title: "Get $BLOOM market data",
  description: "Read live $BLOOM market data on Base (price in USD, 24h change, 24h volume, liquidity, market cap) plus the current ETH spot price used for predictions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_input, ctx) => {
    const [bloomRes, ethRes] = await Promise.all([
      fetch(`https://api.dexscreener.com/latest/dex/tokens/${BLOOM_TOKEN_ADDRESS}`, {
        signal: ctx.signal
      }),
      fetch("https://api.coinbase.com/v2/prices/ETH-USD/spot", { signal: ctx.signal })
    ]);
    const bloomJson = bloomRes.ok ? await bloomRes.json() : null;
    const ethJson = ethRes.ok ? await ethRes.json() : null;
    const pair = bloomJson?.pairs?.[0];
    const data = {
      bloom: {
        tokenAddress: BLOOM_TOKEN_ADDRESS,
        chain: "base",
        priceUsd: pair ? Number(pair.priceUsd ?? 0) : null,
        priceChange24hPercent: pair?.priceChange?.h24 ?? null,
        volume24hUsd: pair?.volume?.h24 ?? null,
        liquidityUsd: pair?.liquidity?.usd ?? null,
        marketCapUsd: pair?.marketCap ?? pair?.fdv ?? null
      },
      ethSpotUsd: ethJson?.data?.amount ? Number(ethJson.data.amount) : null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/prepare-bet.ts
init_define_import_meta_env();
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
import { encodeFunctionData, parseUnits } from "npm:viem@^2.43.3";
init_BloomBetting();
var prepare_bet_default = defineTool6({
  name: "prepare_bet",
  title: "Prepare a prediction transaction",
  description: "Build the unsigned Base transaction(s) needed to predict UP or DOWN on the current ETH round with $BLOOM. Returns an optional ERC-20 approval call plus the placeBet call, to be signed and sent by the caller's own wallet. Nothing is signed or submitted here.",
  inputSchema: {
    address: z4.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("The wallet address that will sign and send the transaction."),
    direction: z4.enum(["up", "down"]).describe("Predicted ETH direction for this round."),
    amountBloom: z4.number().positive().describe("Stake size in whole $BLOOM tokens (not wei).")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ address, direction, amountBloom }) => {
    const amountWei = parseUnits(String(amountBloom), 18);
    const [bettingOpen, round, minimumStake, balance, allowance] = await Promise.all([
      readBetting("isBettingOpen"),
      readBetting("getCurrentRound"),
      readBetting("minimumStake"),
      readToken("balanceOf", [address]),
      readToken("allowance", [address, BLOOM_BETTING_ADDRESS])
    ]);
    const roundId = Number(round.roundId);
    const alreadyBet = await readBetting("hasUserBetInRound", [round.roundId, address]);
    const problems = [];
    if (!bettingOpen) problems.push("Betting is closed for the current round.");
    if (alreadyBet) problems.push(`This wallet already placed a bet in round ${roundId}.`);
    if (amountWei < minimumStake)
      problems.push(`Stake is below the minimum of ${formatBloom(minimumStake)} $BLOOM.`);
    if (balance < amountWei)
      problems.push(`Wallet holds only ${formatBloom(balance)} $BLOOM.`);
    if (problems.length > 0) {
      return {
        content: [{ type: "text", text: problems.join(" ") }],
        isError: true
      };
    }
    const transactions = [];
    if (allowance < amountWei) {
      transactions.push({
        step: "approve",
        chainId: 8453,
        to: BLOOM_TOKEN_ADDRESS,
        data: encodeFunctionData({
          abi: ERC20_ABI,
          functionName: "approve",
          args: [BLOOM_BETTING_ADDRESS, amountWei]
        }),
        value: "0"
      });
    }
    transactions.push({
      step: "placeBet",
      chainId: 8453,
      to: BLOOM_BETTING_ADDRESS,
      data: encodeFunctionData({
        abi: BLOOM_BETTING_ABI,
        functionName: "placeBet",
        args: [direction === "up" ? 1 : 2, amountWei]
      }),
      value: "0"
    });
    const data = {
      network: "base",
      chainId: 8453,
      roundId,
      direction,
      amountBloom,
      amountWei: amountWei.toString(),
      potentialPayoutBloom: amountBloom * 2,
      secondsRemaining: Number(round.endTime) - Math.floor(Date.now() / 1e3),
      transactions,
      note: "Sign and broadcast these transactions in order from the given wallet. Draws count as a loss; payouts are 2x."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hyperwave-predict",
  title: "HyperWave Predict",
  version: "0.1.0",
  instructions: "Tools for HyperWave Predict, an ETH up/down prediction game on Base staked in $BLOOM. Use get_current_round for the live round, get_round for history, get_player_stats for a wallet's record, get_leaderboard for rankings and get_bloom_market for prices. Use prepare_bet to build unsigned Base transactions the caller signs with its own wallet; this server never signs or holds funds.",
  tools: [
    get_current_round_default,
    get_round_default,
    get_player_stats_default,
    get_leaderboard_default,
    get_bloom_market_default,
    prepare_bet_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
